#------------------------------------------------------------------------------
#CHESS TIPS
#------------------------------------------------------------------------------

#File containing a list of chess tips for players to see mainly for a beginner friendly atmosphere.
#This is just a big list of chess tips that can literally just be used to display in the main menu.
#These tips will also be displayed in the win, draw, and lose windows as a nice touch at the end of a game.

#------------------------------------------------------------------------------
#Main tips / hints list
#------------------------------------------------------------------------------s

advice_list = [
    "Control the center of the board with your pawns and pieces.",
    "Develop your knights and bishops early.",
    "Don't move the same piece multiple times in the opening.",
    "Castle early to protect your king.",
    "Avoid moving too many pawns in the opening.",
    "Connect your rooks by moving your queen.",
    "Keep your king safe by not opening up the back rank.",
    "Think before you move; always check for threats.",
    "Don't bring your queen out too early.",
    "Try to develop all your pieces before launching an attack.",
    "Watch for hanging pieces—those that are undefended.",
    "Use your knights before bishops in closed positions.",
    "Keep your pieces protected by pawns or other pieces.",
    "Avoid making unnecessary pawn moves.",
    "Control open files with your rooks.",
    "Plan your moves ahead, at least a few turns.",
    "Try to keep your pieces active rather than passive.",
    "Avoid trading pieces without a good reason.",
    "Don't make random moves; have a purpose.",
    "Use your pawns to control key squares.",
    "Keep your pieces coordinated and connected.",
    "Don't put your pieces where they block each other.",
    "Look for forks, pins, and skewers.",
    "Practice spotting tactics regularly.",
    "Learn basic checkmates like king and queen vs king.",
    "Avoid weakening your king's position unnecessarily.",
    "Don't move your pawns in front of your castled king without reason.",
    "Bring your rooks to the center or open files.",
    "Keep your knight near the center of the board.",
    "Try to occupy the center with your pieces, not just pawns.",
    "Avoid moving your queen to squares where it can be attacked easily.",
    "Trade pieces when you have a material advantage.",
    "Keep pressure on your opponent's weak points.",
    "Don't block your own bishops with pawns.",
    "Avoid moving pieces to the edge of the board too early.",
    "Think about both defense and attack.",
    "Use tactical motifs like discovered attacks.",
    "Try to improve your worst-placed piece each move.",
    "Avoid leaving pieces undefended near your king.",
    "Use your knights to jump over blocked pawns.",
    "Always look for checks before other moves.",
    "Try to control key squares in your opponent's territory.",
    "Don't rush your moves; take your time in critical positions.",
    "Keep pawns connected to avoid isolated pawns.",
    "Avoid doubling your pawns unless necessary.",
    "Don't make too many pawn moves while ignoring development.",
    "Consider your opponent's threats before attacking.",
    "Use your queen to coordinate attacks with other pieces.",
    "Bring your rooks behind passed pawns.",
    "Try to open lines for your bishops and rooks.",
    "Avoid trapping your own pieces.",
    "Use pins to immobilize your opponent's pieces.",
    "Keep the bishop pair if the position is open.",
    "Avoid exchanging bishops if it weakens your position.",
    "Look for back-rank threats in both attack and defense.",
    "Push your pawns to create space when safe.",
    "Don't create weaknesses in your pawn structure unnecessarily.",
    "Keep an eye on your opponent's tactical threats.",
    "Try to anticipate your opponent's plan.",
    "Keep your king safe during the middlegame.",
    "Don't move your pieces multiple times in the opening without reason.",
    "Avoid unnecessary checks that help your opponent.",
    "Try to centralize your pieces in the middlegame.",
    "Trade queens if your king is unsafe.",
    "Use rooks to support pawn advancement.",
    "Avoid trapping your own pawns.",
    "Coordinate your pieces for both attack and defense.",
    "Look for discovered attacks and double attacks.",
    "Try to control key diagonals with your bishops.",
    "Don't weaken your back rank unnecessarily.",
    "Avoid unnecessary sacrifices without clear compensation.",
    "Try to improve your worst piece each turn.",
    "Look for tactics that gain material.",
    "Keep your knight on advanced outposts.",
    "Try to keep your pawn structure flexible.",
    "Don't open files for your opponent's rooks.",
    "Look for opportunities to pin enemy pieces.",
    "Avoid exposing your king to checks.",
    "Don't leave your rooks on the back rank idle.",
    "Coordinate your queen and rooks on open files.",
    "Keep pawns in front of your king solid.",
    "Don't rush to trade pieces without considering the endgame.",
    "Keep your bishops active on long diagonals.",
    "Try to occupy squares where your pieces cannot be attacked.",
    "Avoid weaknesses in your pawn structure near your king.",
    "Don't allow your pieces to be trapped.",
    "Try to push passed pawns with support.",
    "Avoid unnecessary pawn weaknesses.",
    "Look for tactical combinations every turn.",
    "Don't neglect development for pawn moves.",
    "Keep knights near the center for maximum mobility.",
    "Avoid blocking your rooks behind pawns.",
    "Try to keep the initiative if you have an active position.",
    "Look for pins and skewers to gain material.",
    "Don't weaken your king's shelter with pawn moves.",
    "Try to create threats that force your opponent to react.",
    "Keep your pieces active and coordinated.",
    "Don't hang pieces in simple attacks.",
    "Control open files with your rooks early.",
    "Avoid letting your pieces block each other.",
    "Try to improve the position of your least active piece.",
    "Keep pawns connected and supported.",
    "Don't move the same piece multiple times in the opening.",
    "Use your queen carefully; don't expose it too early.",
    "Try to castle early to secure your king.",
    "Avoid moving pawns unnecessarily near your king.",
    "Coordinate rooks and queen for attacks on open files.",
    "Keep your bishops and knights active and central.",
    "Don't allow your opponent to dominate the center.",
    "Try to trade pieces when ahead in material.",
    "Avoid unnecessary pawn weaknesses in front of your king.",
    "Develop pieces before launching attacks.",
    "Use tactics like forks, pins, and skewers to gain advantage.",
    "Keep your king safe; don't open files near it unnecessarily.",
    "Try to control squares in the center and opponent's territory.",
    "Avoid overextending pawns without support.",
    "Bring rooks to open files where they are most effective.",
    "Use knights to attack weak squares in enemy territory.",
    "Don't make hasty moves; think about the consequences.",
    "Try to anticipate opponent's threats before making moves.",
    "Keep pawns and pieces coordinated for defense and attack.",
    "Avoid unnecessary exchanges that favor your opponent.",
    "Try to activate all your pieces in the middlegame.",
    "Look for tactical opportunities each move.",
    "Don't leave pieces undefended or hanging.",
    "Keep rooks on the 7th rank when possible for pressure.",
    "Use your bishops on long diagonals to control space.",
    "Avoid weakening pawn structures near your king.",
    "Try to control the center with pieces, not just pawns.",
    "Don't overcommit to attacks without development.",
    "Keep your pieces flexible for both defense and attack.",
    "Avoid passive pieces; try to keep them active.",
    "Look for checks and captures each turn before quiet moves.",
    "Try to maintain the initiative in open positions.",
    "Don't block your own pieces with pawns.",
    "Keep an eye on your opponent's threats before moving.",
    "Try to trade pieces when it improves your position.",
    "Avoid moving pawns in front of castled king unnecessarily.",
    "Keep knights on strong squares near the center.",
    "Don't allow your opponent to dominate open files.",
    "Use your queen and rooks together for coordinated attacks.",
    "Try to control critical squares in the middlegame.",
    "Avoid unnecessary pawn weaknesses on the board.",
    "Keep your pieces protected and supported by others.",
    "Don't rush to attack; build up position first.",
    "Try to limit your opponent's piece activity.",
    "Avoid giving away open files for your opponent's rooks.",
    "Keep pressure on weak pawns and squares in opponent's camp.",
    "Try to improve your least active piece each turn.",
    "Don't expose your king to unnecessary checks.",
    "Use tactics to gain material advantage.",
    "Keep pawns connected to avoid isolated weaknesses.",
    "Try to occupy outposts with knights and other pieces.",
    "Avoid leaving pieces on squares where they can be attacked easily.",
    "Bring rooks to open files to maximize their impact.",
    "Try to use all pieces effectively, not just pawns and queen.",
    "Avoid unnecessary trades that worsen your pawn structure.",
    "Keep the bishop pair if position is open.",
    "Don't allow back-rank threats to your king.",
    "Try to create threats that your opponent cannot ignore.",
    "Keep your king safe, even in the endgame.",
    "Avoid making random moves without a clear purpose.",
    "Try to anticipate your opponent's tactical ideas.",
    "Keep knights active in the center and near weak squares.",
    "Don't weaken your pawn structure near your king unnecessarily.",
    "Use rooks to support passed pawns when possible.",
    "Try to control diagonals with your bishops.",
    "Avoid placing pieces on the edge unless necessary.",
    "Keep pressure on key squares in your opponent's camp.",
    "Don't overextend pawns without support.",
    "Try to improve all your pieces before attacking.",
    "Avoid exposing your queen without support.",
    "Keep pawns solid to maintain a strong structure.",
    "Try to control key files with rooks and queen.",
    "Don't leave pieces undefended near the center.",
    "Keep your pieces active, especially in closed positions.",
    "Avoid making the same mistakes repeatedly; learn from each game.",
    "Try to keep initiative and force your opponent to respond.",
    "Keep rooks connected and on open files when possible.",
    "Avoid unnecessary pawn moves that weaken your position.",
    "Try to control the center with both pawns and pieces.",
    "Keep your bishop and knight pairs coordinated.",
    "Don't allow opponent's pieces to dominate the center.",
    "Use tactical motifs like forks and pins effectively.",
    "Try to anticipate opponent's threats and plan defense.",
    "Keep your king safe, especially before the endgame.",
    "Avoid blocking your own rooks with pawns or pieces.",
    "Try to maintain active pieces and open lines.",
    "Don't leave pawns isolated or backward unnecessarily.",
    "Use all pieces in coordination during an attack.",
    "Try to spot simple tactics before complex ones.",
    "Keep the center under control throughout the game.",
    "Avoid weakening pawn structures near key squares.",
    "Use your queen and rooks to pressure opponent's weaknesses.",
    "Try to improve pieces that have little activity.",
    "Don't rush moves; think about both defense and attack.",
    "Keep your knights in central squares for maximum mobility.",
    "Avoid trading pieces that improve opponent's position.",
    "Try to control open lines and diagonals for rooks and bishops.",
    "Keep pawns connected to prevent weaknesses.",
    "Avoid unnecessary moves that lose tempo.",
    "Try to maintain balance between attack and defense.",
    "Keep your king safe from tactics and threats.",
    "Don't make unnecessary sacrifices without compensation.",
    "Try to use all pieces effectively in attacks and defense.",
    "Keep an eye on opponent's tactical threats each move.",
    "Avoid leaving back rank vulnerable to threats.",
    "Try to improve your worst pieces to maximize efficiency.",
    "Keep pieces coordinated for both attack and defense.",
    "Don't ignore the center; controlling it is crucial.",
    "Try to trade pieces when ahead in material for simplification.",
    "Keep pawns flexible to support both attack and defense.",
    "Avoid unnecessary checks that help your opponent.",
    "Try to anticipate your opponent's plans and react accordingly.",
    "Keep rooks active and on open files when possible.",
    "Don't block your bishops or rooks with pawns unnecessarily.",
    "Try to control critical squares in opponent's territory.",
    "Keep your queen protected while being active.",
    "Avoid weaknesses in pawn structure around your king.",
    "Try to maintain initiative throughout the middlegame.",
    "Keep pieces coordinated for tactical opportunities.",
    "Don't move the same piece multiple times in the opening unnecessarily.",
    "Try to plan both attack and defense simultaneously.",
    "Keep an eye on weak pawns in your opponent's camp.",
    "Avoid unnecessary pawn moves that weaken your structure.",
    "Try to create threats that force your opponent to respond.",
    "Keep knights and bishops active and central whenever possible.",
    "Don't neglect development for an early attack.",
    "Try to control open files and diagonals with rooks and bishops.",
    "Keep your king safe through castling and pawn cover.",
    "Avoid exposing your queen or rooks prematurely.",
    "Try to anticipate tactical threats and opportunities every turn.",
    "Keep pieces coordinated to support each other and control key squares.",
    "Don't rush moves; think about consequences for both sides."
]
